'use client';

import { useState, useEffect } from 'react';
import { Sidebar } from '@/components/Sidebar';
import { SignalCard } from '@/components/SignalCard';
import { PortfolioStats } from '@/components/PortfolioStats';
import { SignalGenerator } from '@/components/SignalGenerator';
import { CompletedSignalsTable } from '@/components/CompletedSignalsTable';
import { NotificationPermission } from '@/components/NotificationPermission';
import { NotificationSettings } from '@/components/NotificationSettings';
import { AutoGenerateScheduler } from '@/components/AutoGenerateScheduler';
import { CronManager } from '@/components/CronManager';
import { TelegramSettings } from '@/components/TelegramSettings';
import { SignalAnalytics } from '@/components/SignalAnalytics';
import { RefreshCw, Activity, History, AlertCircle, Bell, Zap, Clock, Send, BarChart3 } from 'lucide-react';
import { notificationService } from '@/lib/notification-service';
import { telegramService } from '@/lib/telegram-service';
import axios from 'axios';

const TRACKED_COINS = ['BTC', 'ETH', 'BNB', 'SOL'];

export default function TradingSignalsPage() {
    const [activeTab, setActiveTab] = useState<'active' | 'completed'>('active');

    // States
    const [activeSignals, setActiveSignals] = useState<any[]>([]);
    const [completedSignals, setCompletedSignals] = useState<any[]>([]);
    const [portfolio, setPortfolio] = useState<any>(null);

    // Loading states
    const [generatingSignal, setGeneratingSignal] = useState(false);
    const [loadingActive, setLoadingActive] = useState(true);
    const [loadingCompleted, setLoadingCompleted] = useState(false);
    const [loadingPortfolio, setLoadingPortfolio] = useState(true);
    const [updatingPrices, setUpdatingPrices] = useState(false);
    const [autoGenerating, setAutoGenerating] = useState(false);

    // UI states
    const [autoRefresh, setAutoRefresh] = useState(true);
    const [lastRefresh, setLastRefresh] = useState<Date>(new Date());
    const [isMounted, setIsMounted] = useState(false);
    const [showNotificationSettings, setShowNotificationSettings] = useState(false);
    const [showTelegramSettings, setShowTelegramSettings] = useState(false);
    const [showAnalytics, setShowAnalytics] = useState(false);
    const [showCronManager, setShowCronManager] = useState(false);

    // Load data on mount
    useEffect(() => {
        loadActiveSignals();
        loadPortfolio();
        setIsMounted(true);
    }, []);

    // Auto-refresh prices every 30 seconds
    useEffect(() => {
        if (!autoRefresh) return;

        console.log('🔄 Auto-refresh enabled (every 15s)');

        const refreshInterval = setInterval(async () => {
            console.log('🔄 Auto-refreshing data...', new Date().toLocaleTimeString());

            try {
                // Update prices for active signals
                if (activeSignals.length > 0) {
                    await updateSignalPrices();
                }

                // Reload portfolio stats
                await loadPortfolio();

                // If on completed tab, refresh completed signals too
                if (activeTab === 'completed') {
                    await loadCompletedSignals();
                }
            } catch (error) {
                console.error('Auto-refresh error:', error);
            }
        }, 30000); // 30 seconds

        return () => {
            console.log('🛑 Auto-refresh disabled');
            clearInterval(refreshInterval);
        };
    }, [autoRefresh, activeTab, activeSignals.length]);

    // Get notification settings
    const getNotificationSettings = () => {
        if (typeof window === 'undefined') return null;
        const saved = localStorage.getItem('notification-settings');
        if (saved) {
            return JSON.parse(saved);
        }
        return {
            newSignals: true,
            tpHits: true,
            slHits: true,
            priceAlerts: true,
            autoGenerate: true
        };
    };

    // Send notification for new signal
    const notifyNewSignal = async (signal: any) => {
        const settings = getNotificationSettings();
        if (settings?.newSignals && notificationService.isGranted()) {
            await notificationService.notifyNewSignal(signal);
        }
    };

    // Send notification for auto-generate
    const notifyAutoGenerate = async (count: number, excellentCount: number) => {
        const settings = getNotificationSettings();
        if (settings?.autoGenerate && notificationService.isGranted()) {
            await notificationService.notifyAutoGenerated(count, excellentCount);
        }
    };

    // Load active signals
    const loadActiveSignals = async () => {
        setLoadingActive(true);
        try {
            const response = await axios.get('/api/signals/active');
            if (response.data.success) {
                setActiveSignals(response.data.signals);
            }
        } catch (error) {
            console.error('Error loading active signals:', error);
        } finally {
            setLoadingActive(false);
        }
    };

    // Load completed signals
    const loadCompletedSignals = async () => {
        setLoadingCompleted(true);
        try {
            const response = await axios.get('/api/signals/completed?limit=50');
            if (response.data.success) {
                setCompletedSignals(response.data.signals);
            }
        } catch (error) {
            console.error('Error loading completed signals:', error);
        } finally {
            setLoadingCompleted(false);
        }
    };

    // Load portfolio stats
    const loadPortfolio = async () => {
        setLoadingPortfolio(true);
        try {
            const response = await axios.get('/api/signals/portfolio');
            if (response.data.success) {
                setPortfolio(response.data.portfolio);
            }
        } catch (error) {
            console.error('Error loading portfolio:', error);
        } finally {
            setLoadingPortfolio(false);
        }
    };

    // Update signal prices
    const updateSignalPrices = async () => {
        if (activeSignals.length === 0) return;

        setUpdatingPrices(true);
        try {
            await axios.get('/api/signals/update-prices');
            // Reload active signals and portfolio after update
            await Promise.all([
                loadActiveSignals(),
                loadPortfolio()
            ]);
            setLastRefresh(new Date());
            console.log('✅ Prices updated successfully at', new Date().toLocaleTimeString());
        } catch (error) {
            console.error('Error updating prices:', error);
        } finally {
            setUpdatingPrices(false);
        }
    };

    // Generate new signal
    const handleGenerateSignal = async (coin: string, capital: number) => {
        setGeneratingSignal(true);
        try {
            const response = await axios.post('/api/signals/generate', {
                coin,
                capital
            });

            if (response.data.success) {
                const signal = response.data.signal;

                // Show success message
                const qualityEmoji =
                    signal.quality?.rating === 'EXCELLENT' ? '💎' :
                        signal.quality?.rating === 'GOOD' ? '✨' :
                            signal.quality?.rating === 'FAIR' ? '⚡' : '❓';

                alert(`✅ Signal generated for ${coin}!\n\n${qualityEmoji} Quality: ${signal.quality?.rating || 'N/A'} (${signal.quality?.score || 0}/100)\nAction: ${signal.action}\nConfidence: ${signal.confidence}%\nEntry: $${signal.entryPrice.toLocaleString()}\nR:R: ${signal.riskRewardRatio}:1\n\n${signal.quality?.rating === 'EXCELLENT' || signal.quality?.rating === 'GOOD' ? '✅ This is a quality signal! Check Active Signals tab.' : '⚠️ This signal was not saved (quality too low).'}`);

                // Send notifications
                await notifyNewSignal(signal);

                // Send Telegram
                if (signal.quality?.rating === 'EXCELLENT' || signal.quality?.rating === 'GOOD') {
                    await telegramService.notifyNewSignal(signal);
                }

                // Reload data
                await Promise.all([
                    loadActiveSignals(),
                    loadPortfolio()
                ]);
            }
        } catch (error: any) {
            console.error('Error generating signal:', error);
            alert('❌ Failed to generate signal: ' + (error.response?.data?.error || error.message));
        } finally {
            setGeneratingSignal(false);
        }
    };

    // Auto-generate signals for all coins
    const handleAutoGenerate = async () => {
        setAutoGenerating(true);
        try {
            const response = await axios.post('/api/signals/auto-generate', {
                coins: TRACKED_COINS,
                capital: 1000
            });

            if (response.data.success) {
                const signals = response.data.signals;
                const excellentCount = signals.filter((s: any) => s.quality?.rating === 'EXCELLENT').length;
                const goodCount = signals.filter((s: any) => s.quality?.rating === 'GOOD').length;

                if (signals.length === 0) {
                    alert(`⚠️ No quality signals generated\n\nAll analyzed coins failed to meet quality criteria (Confidence >70%, R:R >2:1).\n\nTry again later when market conditions improve.`);
                } else {
                    alert(`🤖 Auto-generated ${signals.length} quality signals!\n\n💎 EXCELLENT: ${excellentCount}\n✨ GOOD: ${goodCount}\n\nCheck your Active Signals tab!`);

                    // Send browser notification
                    await notifyAutoGenerate(signals.length, excellentCount);

                    // Send Telegram notification
                    await telegramService.notifyAutoGenerated(signals.length, excellentCount, goodCount);
                }

                // Reload data
                await Promise.all([
                    loadActiveSignals(),
                    loadPortfolio()
                ]);
            }
        } catch (error: any) {
            console.error('Error auto-generating signals:', error);
            alert('❌ Failed to auto-generate signals: ' + (error.response?.data?.error || error.message));
        } finally {
            setAutoGenerating(false);
        }
    };

    // Close signal manually
    const handleCloseSignal = async (signalId: string) => {
        if (!confirm('Are you sure you want to close this position?')) return;

        try {
            const response = await axios.post('/api/signals/close', {
                signalId
            });

            if (response.data.success) {
                alert(`✅ Position closed!\n\nP/L: $${response.data.pnl.usd} (${response.data.pnl.percentage}%)`);

                // Reload data
                await Promise.all([
                    loadActiveSignals(),
                    loadPortfolio()
                ]);
            }
        } catch (error: any) {
            console.error('Error closing signal:', error);
            alert('❌ Failed to close signal: ' + (error.response?.data?.error || error.message));
        }
    };

    // Manual refresh all
    const handleRefreshAll = async () => {
        await Promise.all([
            updateSignalPrices(),
            loadPortfolio()
        ]);
    };

    // Load completed signals when switching tabs
    useEffect(() => {
        if (activeTab === 'completed' && completedSignals.length === 0) {
            loadCompletedSignals();
        }
    }, [activeTab]);

    // Count excellent and good signals
    const excellentSignalsCount = activeSignals.filter(s => s.quality?.rating === 'EXCELLENT').length;
    const goodSignalsCount = activeSignals.filter(s => s.quality?.rating === 'GOOD').length;

    return (
        <div className="flex min-h-screen bg-gray-50">
            <Sidebar />

            <main className="flex-1 ml-64">
                <div className="max-w-[1800px] mx-auto p-6">

                    {/* Header */}
                    <div className="mb-6">
                        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-4">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 bg-gradient-to-br from-[#ff6726] to-[#ff8f5e] rounded-lg flex items-center justify-center">
                                    <Activity className="text-white" size={24} />
                                </div>
                                <div>
                                    <h1 className="text-3xl font-bold text-gray-900">Trading Signals</h1>
                                    <p className="text-gray-600">AI-powered semi-auto trading system</p>
                                </div>
                            </div>

                            <div className="flex flex-wrap items-center gap-3">
                                {/* Analytics Button */}
                                <button
                                    onClick={() => setShowAnalytics(!showAnalytics)}
                                    className="px-4 py-2 bg-purple-600 text-white rounded-lg font-medium hover:bg-purple-700 transition-colors flex items-center gap-2"
                                >
                                    <BarChart3 size={16} />
                                    <span>Analytics</span>
                                </button>

                                {/* Telegram Settings Button */}
                                <button
                                    onClick={() => setShowTelegramSettings(!showTelegramSettings)}
                                    className="px-4 py-2 bg-blue-500 text-white rounded-lg font-medium hover:bg-blue-600 transition-colors flex items-center gap-2"
                                >
                                    <Send size={16} />
                                    <span>Telegram</span>
                                </button>

                                {/* Development: Cron Manager */}
                                {process.env.NODE_ENV === 'development' && (
                                    <button
                                        onClick={() => setShowCronManager(!showCronManager)}
                                        className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center gap-2"
                                    >
                                        <Clock size={16} />
                                        <span>Cron Jobs</span>
                                    </button>
                                )}

                                {/* Notification Settings Button */}
                                <button
                                    onClick={() => setShowNotificationSettings(!showNotificationSettings)}
                                    className={`px-4 py-2 rounded-lg font-medium transition-all flex items-center gap-2 ${showNotificationSettings
                                        ? 'bg-[#ff6726] text-white shadow-lg'
                                        : 'bg-white border-2 border-gray-200 text-gray-700 hover:bg-gray-50'
                                        }`}
                                >
                                    <Bell size={16} />
                                    <span>Notifications</span>
                                </button>

                                {/* Auto-refresh toggle with last refresh time */}
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={() => setAutoRefresh(!autoRefresh)}
                                        className={`px-4 py-2 rounded-lg font-medium transition-colors ${autoRefresh
                                            ? 'bg-green-100 text-green-700 border-2 border-green-300'
                                            : 'bg-gray-100 text-gray-600 border-2 border-gray-300'
                                            }`}
                                    >
                                        {autoRefresh ? '🟢 Auto' : '⚪ Manual'}
                                    </button>

                                    {autoRefresh && isMounted && (
                                        <div className="text-xs text-gray-500 flex items-center gap-1 bg-white px-2 py-1 rounded border border-gray-200">
                                            <RefreshCw size={12} className={updatingPrices ? 'animate-spin text-green-600' : 'text-gray-400'} />
                                            <span suppressHydrationWarning>
                                                Last: {lastRefresh.toLocaleTimeString()}
                                            </span>
                                        </div>
                                    )}
                                </div>

                                {/* Manual refresh button */}
                                <button
                                    onClick={handleRefreshAll}
                                    disabled={updatingPrices}
                                    className="flex items-center gap-2 px-5 py-2.5 bg-white border-2 border-gray-200 rounded-lg hover:bg-gray-50 transition-colors shadow-sm disabled:opacity-50"
                                >
                                    <RefreshCw size={16} className={updatingPrices ? 'animate-spin' : ''} />
                                    <span className="font-medium">Refresh</span>
                                </button>
                            </div>
                        </div>

                        {/* Settings Panels */}
                        {showAnalytics && (
                            <div className="mb-6">
                                <SignalAnalytics signals={[...activeSignals, ...completedSignals]} />
                            </div>
                        )}

                        {showTelegramSettings && (
                            <div className="mb-6">
                                <TelegramSettings />
                            </div>
                        )}

                        {showCronManager && process.env.NODE_ENV === 'development' && (
                            <div className="mb-6">
                                <CronManager />
                            </div>
                        )}

                        {showNotificationSettings && (
                            <div className="mb-6">
                                <NotificationSettings />
                            </div>
                        )}

                        {/* Info Banner */}
                        <div className="bg-gradient-to-r from-blue-50 to-purple-50 border-2 border-blue-200 rounded-lg p-4 flex items-start gap-3">
                            <AlertCircle className="text-blue-600 flex-shrink-0 mt-0.5" size={20} />
                            <div className="text-sm text-blue-900">
                                <p className="font-semibold mb-1">📊 Semi-Auto Trading Mode</p>
                                <ul className="space-y-1 text-blue-800">
                                    <li>• 🤖 AI analyzes market and generates quality signals (Confidence &gt;70%, R:R &gt;2:1)</li>
                                    <li>• 💎 Only EXCELLENT and GOOD signals are saved automatically</li>
                                    <li>• 📋 Click &quot;Trade Now&quot; to copy signal info and execute on your exchange</li>
                                    <li>• 🔔 Get browser & Telegram notifications for new signals and TP/SL hits</li>
                                    <li>• 🔄 Auto-refresh enabled: Prices update every 30 seconds</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {/* Main Grid */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">

                        {/* Left Column - Signal Generator & Scheduler */}
                        <div className="lg:col-span-1 space-y-6">
                            {/* Signal Generator */}
                            <SignalGenerator
                                coins={TRACKED_COINS}
                                onGenerate={handleGenerateSignal}
                                loading={generatingSignal}
                            />

                            {/* Auto-Generate Button */}
                            <button
                                onClick={handleAutoGenerate}
                                disabled={autoGenerating}
                                className="w-full py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold text-lg hover:shadow-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3"
                            >
                                {autoGenerating ? (
                                    <>
                                        <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                                        <span>Auto-Generating...</span>
                                    </>
                                ) : (
                                    <>
                                        <Zap size={20} />
                                        <span>Auto-Generate All Signals</span>
                                    </>
                                )}
                            </button>

                            {/* Auto-Generate Scheduler */}
                            <AutoGenerateScheduler
                                onAutoGenerate={handleAutoGenerate}
                            />

                            {/* Info Box */}
                            <div className="bg-purple-50 border-2 border-purple-200 rounded-lg p-4">
                                <div className="flex items-start gap-3">
                                    <span className="text-2xl">🤖</span>
                                    <div>
                                        <p className="font-bold text-purple-900 mb-1">Auto-Generate</p>
                                        <p className="text-sm text-purple-800">
                                            Analyzes all 4 coins and generates only quality signals (EXCELLENT or GOOD) automatically. Use the scheduler to run at intervals.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Right Column - Portfolio Stats */}
                        <div className="lg:col-span-2">
                            <PortfolioStats
                                portfolio={portfolio}
                                loading={loadingPortfolio}
                            />
                        </div>
                    </div>

                    {/* Tabs */}
                    <div className="bg-white rounded-lg border-2 border-gray-200 mb-6">
                        <div className="flex border-b border-gray-200">
                            <button
                                onClick={() => setActiveTab('active')}
                                className={`flex-1 py-4 px-6 font-semibold transition-colors ${activeTab === 'active'
                                    ? 'text-[#ff6726] border-b-2 border-[#ff6726] bg-orange-50'
                                    : 'text-gray-600 hover:bg-gray-50'
                                    }`}
                            >
                                <div className="flex items-center justify-center gap-2">
                                    <Activity size={20} />
                                    <span>Active Signals ({activeSignals.length})</span>
                                    {excellentSignalsCount > 0 && (
                                        <span className="ml-2 px-2 py-0.5 bg-green-500 text-white text-xs rounded-full font-bold">
                                            {excellentSignalsCount} 💎
                                        </span>
                                    )}
                                    {goodSignalsCount > 0 && (
                                        <span className="ml-2 px-2 py-0.5 bg-blue-500 text-white text-xs rounded-full font-bold">
                                            {goodSignalsCount} ✨
                                        </span>
                                    )}
                                </div>
                            </button>

                            <button
                                onClick={() => setActiveTab('completed')}
                                className={`flex-1 py-4 px-6 font-semibold transition-colors ${activeTab === 'completed'
                                    ? 'text-[#ff6726] border-b-2 border-[#ff6726] bg-orange-50'
                                    : 'text-gray-600 hover:bg-gray-50'
                                    }`}
                            >
                                <div className="flex items-center justify-center gap-2">
                                    <History size={20} />
                                    <span>Completed ({completedSignals.length})</span>
                                </div>
                            </button>
                        </div>
                    </div>

                    {/* Active Signals Tab */}
                    {activeTab === 'active' && (
                        <div>
                            {loadingActive ? (
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                    {[1, 2, 3].map(i => (
                                        <div key={i} className="bg-white rounded-lg border border-gray-200 p-6 animate-pulse">
                                            <div className="space-y-4">
                                                <div className="h-8 bg-gray-200 rounded w-1/2"></div>
                                                <div className="h-32 bg-gray-200 rounded"></div>
                                                <div className="h-24 bg-gray-200 rounded"></div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : activeSignals.length === 0 ? (
                                <div className="bg-white rounded-lg border-2 border-dashed border-gray-300 p-12 text-center">
                                    <Activity className="mx-auto text-gray-400 mb-4" size={64} />
                                    <h3 className="text-xl font-bold text-gray-900 mb-2">No Active Signals</h3>
                                    <p className="text-gray-600 mb-6">Generate your first signal to start trading</p>
                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-3xl mx-auto text-sm">
                                        <div className="flex flex-col items-center gap-2 p-4 bg-orange-50 rounded-lg border border-orange-200">
                                            <span className="w-8 h-8 bg-[#ff6726] rounded-full flex items-center justify-center text-white font-bold">1</span>
                                            <span className="font-semibold text-gray-900">Generate Signal</span>
                                            <span className="text-gray-600 text-center">For single coin analysis</span>
                                        </div>
                                        <div className="flex flex-col items-center gap-2 p-4 bg-purple-50 rounded-lg border border-purple-200">
                                            <span className="w-8 h-8 bg-purple-600 rounded-full flex items-center justify-center text-white font-bold">2</span>
                                            <span className="font-semibold text-gray-900">Auto-Generate</span>
                                            <span className="text-gray-600 text-center">Analyze all 4 coins at once</span>
                                        </div>
                                        <div className="flex flex-col items-center gap-2 p-4 bg-blue-50 rounded-lg border border-blue-200">
                                            <span className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold">3</span>
                                            <span className="font-semibold text-gray-900">Enable Scheduler</span>
                                            <span className="text-gray-600 text-center">Automatic signal generation</span>
                                        </div>
                                    </div>
                                </div>
                            ) : (
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                    {activeSignals.map(signal => (
                                        <SignalCard
                                            key={signal.id}
                                            signal={signal}
                                            onClose={handleCloseSignal}
                                        />
                                    ))}
                                </div>
                            )}
                        </div>
                    )}

                    {/* Completed Signals Tab */}
                    {activeTab === 'completed' && (
                        <CompletedSignalsTable
                            signals={completedSignals}
                            loading={loadingCompleted}
                        />
                    )}

                    {/* Footer Info */}
                    <div className="mt-8 bg-gradient-to-r from-purple-50 to-blue-50 border-2 border-purple-200 rounded-lg p-6">
                        <h4 className="font-bold text-purple-900 mb-3 text-lg">📊 Signal Quality Ratings</h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                            <div>
                                <p className="font-semibold text-purple-900 mb-2">Quality Levels:</p>
                                <ul className="space-y-1 text-purple-800">
                                    <li>• <strong>💎 EXCELLENT:</strong> Score ≥80 (Confidence &gt;80%, R:R &gt;4:1)</li>
                                    <li>• <strong>✨ GOOD:</strong> Score ≥65 (Confidence &gt;70%, R:R &gt;2:1)</li>
                                    <li>• <strong>⚡ FAIR:</strong> Score ≥50 (Moderate quality)</li>
                                    <li>• <strong>❌ POOR:</strong> Score &lt;50 (Not saved, not recommended)</li>
                                </ul>
                            </div>
                            <div>
                                <p className="font-semibold text-purple-900 mb-2">How to Trade:</p>
                                <ul className="space-y-1 text-purple-800">
                                    <li>1. Wait for EXCELLENT or GOOD signals (auto-saved)</li>
                                    <li>2. Click &quot;Trade Now&quot; button on signal card</li>
                                    <li>3. Copy the complete trade information</li>
                                    <li>4. Execute on your exchange (Binance/Bybit)</li>
                                    <li>5. Monitor P/L on this dashboard in real-time</li>
                                    <li>6. System auto-checks TP/SL every 5 minutes</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </main>

            {/* Notification Permission Banner */}
            <NotificationPermission />
        </div>
    );
}
