export interface NotificationOptions {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: any;
  requireInteraction?: boolean;
}

class NotificationService {
  private permission: NotificationPermission = 'default';

  constructor() {
    if (typeof window !== 'undefined' && 'Notification' in window) {
      this.permission = Notification.permission;
    }
  }

  // Request permission
  async requestPermission(): Promise<boolean> {
    if (!('Notification' in window)) {
      console.log('Browser does not support notifications');
      return false;
    }

    if (this.permission === 'granted') {
      return true;
    }

    if (this.permission === 'denied') {
      console.log('Notification permission denied');
      return false;
    }

    try {
      const permission = await Notification.requestPermission();
      this.permission = permission;
      return permission === 'granted';
    } catch (error) {
      console.error('Error requesting notification permission:', error);
      return false;
    }
  }

  // Check if notifications are supported and permitted
  isSupported(): boolean {
    return typeof window !== 'undefined' && 'Notification' in window;
  }

  isGranted(): boolean {
    return this.permission === 'granted';
  }

  // Send notification
  async send(options: NotificationOptions): Promise<Notification | null> {
    if (!this.isSupported()) {
      console.log('Notifications not supported');
      return null;
    }

    if (!this.isGranted()) {
      const granted = await this.requestPermission();
      if (!granted) {
        console.log('Notification permission not granted');
        return null;
      }
    }

    try {
      const notification = new Notification(options.title, {
        body: options.body,
        icon: options.icon || '/favicon.ico',
        badge: options.badge || '/favicon.ico',
        tag: options.tag,
        data: options.data,
        requireInteraction: options.requireInteraction || false,
        silent: false
      });

      // Auto close after 10 seconds if not require interaction
      if (!options.requireInteraction) {
        setTimeout(() => notification.close(), 10000);
      }

      // Handle click
      notification.onclick = (event) => {
        event.preventDefault();
        window.focus();
        
        // Navigate to trading signals page if data contains url
        if (options.data?.url) {
          window.location.href = options.data.url;
        }
        
        notification.close();
      };

      return notification;
    } catch (error) {
      console.error('Error sending notification:', error);
      return null;
    }
  }

  // Preset notifications for trading signals
  async notifyNewSignal(signal: any): Promise<void> {
    const emoji = signal.action === 'BUY' ? '🟢' : '🔴';
    const qualityEmoji = 
      signal.quality?.rating === 'EXCELLENT' ? '💎' :
      signal.quality?.rating === 'GOOD' ? '✨' : '⚡';

    await this.send({
      title: `${qualityEmoji} ${signal.quality?.rating || 'New'} Signal: ${signal.coin}`,
      body: `${emoji} ${signal.action} at $${signal.entryPrice.toLocaleString()}\nConfidence: ${signal.confidence}% | R:R: ${signal.riskRewardRatio}:1`,
      tag: `signal-${signal.id}`,
      data: {
        url: '/trading-signals',
        signalId: signal.id
      },
      requireInteraction: true
    });
  }

  async notifyTPHit(signal: any, tpLevel: number): Promise<void> {
    const tpPrice = signal[`takeProfit${tpLevel}`];
    const profit = signal.pnlUSD;

    await this.send({
      title: `🎉 TP${tpLevel} Hit: ${signal.coin}`,
      body: `Target reached at $${tpPrice.toLocaleString()}\nProfit: $${profit.toFixed(2)} (+${signal.pnlPercentage.toFixed(2)}%)`,
      tag: `tp-${signal.id}-${tpLevel}`,
      data: {
        url: '/trading-signals',
        signalId: signal.id
      }
    });
  }

  async notifySLHit(signal: any): Promise<void> {
    const loss = signal.pnlUSD;

    await this.send({
      title: `⚠️ Stop Loss Hit: ${signal.coin}`,
      body: `Position closed at $${signal.currentPrice.toLocaleString()}\nLoss: $${Math.abs(loss).toFixed(2)} (${signal.pnlPercentage.toFixed(2)}%)`,
      tag: `sl-${signal.id}`,
      data: {
        url: '/trading-signals',
        signalId: signal.id
      }
    });
  }

  async notifyAutoGenerated(count: number, excellentCount: number): Promise<void> {
    await this.send({
      title: `🤖 Auto-Generated ${count} New Signals`,
      body: excellentCount > 0 
        ? `${excellentCount} EXCELLENT signals ready to trade!`
        : `Check out the new signals on your dashboard`,
      tag: 'auto-generate',
      data: {
        url: '/trading-signals'
      }
    });
  }

  async notifyPriceAlert(signal: any, alertType: string): Promise<void> {
    await this.send({
      title: `📊 Price Alert: ${signal.coin}`,
      body: `${alertType} - Current: $${signal.currentPrice.toLocaleString()}\nP/L: ${signal.pnlPercentage > 0 ? '+' : ''}${signal.pnlPercentage.toFixed(2)}%`,
      tag: `alert-${signal.id}`,
      data: {
        url: '/trading-signals',
        signalId: signal.id
      }
    });
  }
}

// Export singleton instance
export const notificationService = new NotificationService();
