import axios from 'axios';

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

class TelegramService {
  private apiUrl: string;

  constructor() {
    this.apiUrl = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}`;
  }

  async sendMessage(text: string, parseMode: 'HTML' | 'Markdown' = 'HTML'): Promise<boolean> {
    if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
      console.log('⚠️ Telegram not configured');
      return false;
    }

    try {
      await axios.post(`${this.apiUrl}/sendMessage`, {
        chat_id: TELEGRAM_CHAT_ID,
        text,
        parse_mode: parseMode
      });
      return true;
    } catch (error) {
      console.error('❌ Telegram send error:', error);
      return false;
    }
  }

  async notifyNewSignal(signal: any): Promise<void> {
    const emoji = signal.action === 'BUY' ? '🟢' : '🔴';
    const qualityEmoji = 
      signal.quality?.rating === 'EXCELLENT' ? '💎' :
      signal.quality?.rating === 'GOOD' ? '✨' : '⚡';

    const message = `
${qualityEmoji} <b>${signal.quality?.rating || 'NEW'} SIGNAL</b>

${emoji} <b>${signal.action} ${signal.coin}</b>
Confidence: <b>${signal.confidence}%</b>
Quality Score: <b>${signal.quality?.score || 0}/100</b>

💰 <b>Entry & Targets:</b>
Entry: $${signal.entryPrice.toLocaleString()}
Stop Loss: $${signal.stopLoss.toLocaleString()} (-${((Math.abs(signal.stopLoss - signal.entryPrice) / signal.entryPrice) * 100).toFixed(2)}%)
TP1: $${signal.takeProfit1.toLocaleString()} (+${((signal.takeProfit1 - signal.entryPrice) / signal.entryPrice * 100).toFixed(2)}%)
TP2: $${signal.takeProfit2.toLocaleString()} (+${((signal.takeProfit2 - signal.entryPrice) / signal.entryPrice * 100).toFixed(2)}%)
TP3: $${signal.takeProfit3.toLocaleString()} (+${((signal.takeProfit3 - signal.entryPrice) / signal.entryPrice * 100).toFixed(2)}%)

📊 <b>Position:</b>
Size: ${signal.positionSize} ${signal.coin}
Capital: $${signal.capitalAllocated}
R:R: ${signal.riskRewardRatio}:1

💡 <b>Reasoning:</b>
${signal.reasoning}

⏰ ${new Date().toLocaleString()}
    `.trim();

    await this.sendMessage(message);
  }

  async notifyTPHit(signal: any, tpLevel: number): Promise<void> {
    const tpPrice = signal[`takeProfit${tpLevel}`];
    const message = `
🎉 <b>TP${tpLevel} HIT!</b>

<b>${signal.coin}</b> reached Target ${tpLevel}
Price: $${tpPrice.toLocaleString()}

💰 <b>Profit:</b>
P/L: $${signal.pnlUSD.toFixed(2)}
ROI: +${signal.pnlPercentage.toFixed(2)}%

${tpLevel === 3 ? '🏆 All targets completed!' : `📊 Next target: TP${tpLevel + 1} at $${signal[`takeProfit${tpLevel + 1}`].toLocaleString()}`}

⏰ ${new Date().toLocaleString()}
    `.trim();

    await this.sendMessage(message);
  }

  async notifySLHit(signal: any): Promise<void> {
    const message = `
⚠️ <b>STOP LOSS HIT</b>

<b>${signal.coin}</b> stopped out
Price: $${signal.currentPrice.toLocaleString()}

💸 <b>Loss:</b>
P/L: -$${Math.abs(signal.pnlUSD).toFixed(2)}
ROI: ${signal.pnlPercentage.toFixed(2)}%

Risk management protected your capital.

⏰ ${new Date().toLocaleString()}
    `.trim();

    await this.sendMessage(message);
  }

  async notifyAutoGenerated(count: number, excellentCount: number, goodCount: number): Promise<void> {
    const message = `
🤖 <b>AUTO-GENERATED SIGNALS</b>

Generated: <b>${count} quality signals</b>
💎 EXCELLENT: ${excellentCount}
✨ GOOD: ${goodCount}

Check your dashboard to review and trade!

⏰ ${new Date().toLocaleString()}
    `.trim();

    await this.sendMessage(message);
  }

  async notifyDailySummary(portfolio: any): Promise<void> {
    const isProfit = portfolio.netProfit >= 0;
    const emoji = isProfit ? '📈' : '📉';

    const message = `
${emoji} <b>DAILY SUMMARY</b>

💰 <b>Portfolio:</b>
Current Capital: $${portfolio.currentCapital.toFixed(2)}
Net Profit: ${isProfit ? '+' : ''}$${portfolio.netProfit.toFixed(2)} (${portfolio.netProfitPercentage.toFixed(2)}%)

📊 <b>Performance:</b>
Total Trades: ${portfolio.totalTrades}
Win Rate: ${portfolio.winRate.toFixed(1)}%
Profit Factor: ${portfolio.profitFactor.toFixed(2)}

✅ Winning: ${portfolio.winningTrades} (+$${portfolio.totalProfit.toFixed(2)})
❌ Losing: ${portfolio.losingTrades} (-$${portfolio.totalLoss.toFixed(2)})

🎯 Active Positions: ${portfolio.activePositions}

${isProfit ? '🎉 Great job today!' : '💪 Tomorrow is a new opportunity!'}

⏰ ${new Date().toLocaleString()}
    `.trim();

    await this.sendMessage(message);
  }
}

export const telegramService = new TelegramService();